#!/bin/bash
# Run TCP Client

echo "=========================================="
echo "Starting TCP Client"
echo "=========================================="

# Change to project root
cd "$(dirname "$0")"

# Create logs directory if it doesn't exist
mkdir -p logs

# Check if JAR exists
if [ ! -f "tcp-client/target/tcp-client-1.0.0.jar" ]; then
    echo "ERROR: Client JAR not found!"
    echo "Please run ./bld first to build the project"
    exit 1
fi

export TCP_CLIENT_HOST=${TCP_CLIENT_HOST:-$ip2}
# export TCP_CLIENT_HOST=127.0.0.1
export TCP_CLIENT_PORT=${TCP_CLIENT_PORT:-5039}
export TCP_CLIENT_TIMEOUT=250
export TCP_CLIENT_RETRY_WAIT=270
#terminal, ui, both
export TCP_CLIENT_MODE=ui
echo "Starting client"
echo "Logs: logs/tcp-client.log"
echo "Type 'exit' to quit"
echo "=========================================="
echo ""
# Run the client JAR directly
# java -jar tcp-client/target/tcp-client-1.0.0.jar
  java -DTCP_CLIENT_HOST=$TCP_CLIENT_HOST \
  -jar tcp-client/target/tcp-client-1.0.0.jar \
       --tcp.client.monitoring.enabled=true \
       --tcp.client.monitoring.tick-ms=5000 


