#!/bin/bash
# Run TCP Client

echo "=========================================="
echo "Starting TCP Client"
echo "=========================================="

# Change to project root
cd "$(dirname "$0")"

# Create logs directory if it doesn't exist
mkdir -p logs

# Check if JAR exists
if [ ! -f "tcp-client/target/tcp-client-1.0.0.jar" ]; then
    echo "ERROR: Client JAR not found!"
    echo "Please run ./bld first to build the project"
    exit 1
fi

# export TCP_CLIENT_HOST=${TCP_CLIENT_HOST:-$ip2}
# export TCP_CLIENT_HOST=127.0.0.1
# export TCP_CLIENT_PORT=${TCP_CLIENT_PORT:-5038}
export TCP_CLIENT_TIMEOUT=230
export TCP_CLIENT_RETRY_WAIT=150
#terminal, ui, both
export TCP_CLIENT_MODE=ui
echo "Starting client inside network"
echo "Logs: logs/tcp-client.log"
echo "Type 'exit' to quit"
echo "=========================================="
echo ""
# Run the client JAR directly
xhost +local:

sudo ip netns exec netns_client \
  runuser -u $(whoami) -g $(id -gn) -- \
  env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY \
  java -jar tcp-client/target/tcp-client-1.0.0.jar \
       --tcp.client.host=10.200.2.2 \
       --tcp.client.port=5038 \
       --tcp.client.mode=both